#!/usr/bin/env node

import { createHash } from 'node:crypto'
import {
  copyFile,
  cp,
  lstat,
  mkdir,
  readFile,
  readdir,
  rename,
  rm,
  stat,
  writeFile,
} from 'node:fs/promises'
import { dirname, join, posix, relative, resolve, sep } from 'node:path'
import { fileURLToPath } from 'node:url'

import { categoryGroups, expectedCatalogIds } from './catalog-config.mjs'
import { createThemeBuckets, resolveProduct, selectTheme } from './product-routing.mjs'
import { guideId, planGuide, sourceStatus } from './guide-layout.mjs'

const root = resolve(process.env.TANSTACK_BUILD_ROOT || resolve(dirname(fileURLToPath(import.meta.url)), '..'))
const exampleDir = join(dirname(fileURLToPath(import.meta.url)), 'examples')
const examples = JSON.parse(await readFile(join(exampleDir, 'manifest.json'), 'utf8'))
const skillsDir = join(root, 'skills')
const docSourceDir = join(root, '.tanstack-doc-sources')
const exportManifestPath = join(skillsDir, '.tanstack-skills-export.tsv')
const productMarker = '.tanstack-product-skill.json'
const legacyMarker = '.tanstack-framework-pack.json'
const generator = 'scripts/build-groups.mjs'
const generatedComment = '<!-- Generated by scripts/build-groups.mjs. Do not edit directly. -->'
const ascii = (left, right) => (left < right ? -1 : left > right ? 1 : 0)
const exact = (...names) => (name) => names.includes(name)
const contains = (...parts) => (value) => parts.some((part) => value.includes(part))
const matches = (pattern) => (value) => pattern.test(value)

function theme(key, title, description, match) {
  return { key, title, description, match }
}

function product(id, title, description, options) {
  return { id, title, name: `tanstack-${id}`, description, ...options }
}

const queryPrefix = 'tanstack-query-intent-'
const tableAdapters = ['react', 'preact', 'vue', 'solid', 'svelte', 'angular', 'lit', 'alpine', 'ember', 'octane']
const dbAdapters = ['react', 'vue', 'solid', 'svelte', 'angular']
const startRouterEssentials = new Set([
  'tanstack-router-core',
  'tanstack-router-core-type-safety',
  'tanstack-router-core-path-params',
  'tanstack-router-core-search-params',
  'tanstack-router-core-navigation',
  'tanstack-router-core-data-loading',
  'tanstack-router-core-auth-and-guards',
  'tanstack-router-core-not-found-and-errors',
])
const docFrameworks = {
  charts: ['react', 'preact', 'vue', 'solid', 'svelte', 'angular', 'lit', 'alpine', 'octane', 'react-native'],
  form: ['react', 'preact', 'vue', 'angular', 'solid', 'lit', 'svelte'],
  hotkeys: ['react', 'preact', 'solid', 'svelte', 'vue', 'angular', 'lit'],
  pacer: ['react', 'preact', 'solid', 'angular'],
  store: ['react', 'preact', 'solid', 'svelte', 'vue', 'angular', 'lit', 'octane'],
  virtual: ['react', 'solid', 'vue', 'svelte', 'lit', 'angular', 'marko'],
}

const productSpecs = [
  product('start', 'TanStack Start', 'Full-stack application guidance for TanStack Start, including server functions, middleware, deployment, and framework adapters.', {
    maturity: 'Release candidate. Confirm the installed package version before using an API.',
    atomicMatch: (name) => /^tanstack-(?:start-(?:client|server)-core|(?:react|solid|vue)-start)(?:-|$)/.test(name),
    supplementalAtomicMatch: (name) => /^tanstack-(?:router-core|router-plugin|virtual-file-routes|solid-router|vue-router)(?:-|$)/.test(name),
    themes: [
      theme('foundations', 'Foundations', 'Start architecture and execution model.', (name) =>
        exact('tanstack-start-client-core-start-core', 'tanstack-start-client-core-start-core-execution-model')(name)),
      theme('server-runtime', 'Server runtime', 'Server functions, server routes, and server runtime behavior.', contains('server-functions', 'server-routes', 'tanstack-start-server-core')),
      theme('middleware-auth', 'Middleware and authentication', 'Request middleware and server authentication primitives.', contains('middleware', 'auth-server-primitives')),
      theme('deployment-rendering', 'Deployment and rendering', 'Deployment and server-component guidance.', contains('deployment', 'server-components')),
      theme('framework-react', 'React adapter', 'React Start setup and migration.', (name) => /^tanstack-react-start(?:-|$)/.test(name)),
      theme('framework-solid', 'Solid adapter', 'Solid Start adapter guidance.', exact('tanstack-solid-start')),
      theme('framework-vue', 'Vue adapter', 'Vue Start adapter guidance.', exact('tanstack-vue-start')),
      theme('router-essentials', 'Router essentials', 'Bundled Router foundations, navigation, data, authentication, and error guidance required by Start.', (name, source) => source.supplemental === true && startRouterEssentials.has(name)),
      theme('router-ssr-tooling-adapters', 'Router SSR, tooling, and adapters', 'Bundled Router SSR, code splitting, build tooling, route generation, Solid, and Vue guidance.', (name, source) => source.supplemental === true && !startRouterEssentials.has(name)),
    ],
    frameworks: [
      ['react', '@tanstack/react-start'],
      ['solid', '@tanstack/solid-start'],
      ['vue', '@tanstack/vue-start'],
    ],
    related: ['tanstack-router', 'tanstack-query'],
  }),
  product('router', 'TanStack Router', 'Type-safe routing guidance for navigation, URL state, data loading, authentication, SSR, and framework adapters.', {
    atomicMatch: (name) => /^tanstack-(?:router-core|router-plugin|virtual-file-routes|solid-router|vue-router)(?:-|$)/.test(name),
    themes: [
      theme('foundations', 'Foundations', 'Router construction and type-safety.', exact('tanstack-router-core', 'tanstack-router-core-type-safety')),
      theme('urls-navigation', 'URLs and navigation', 'Path parameters, search parameters, and navigation.', contains('path-params', 'search-params', 'navigation')),
      theme('data-auth-errors', 'Data, authentication, and errors', 'Data loading, guards, not-found, and error boundaries.', contains('data-loading', 'auth-and-guards', 'not-found-and-errors')),
      theme('ssr-build-tooling', 'SSR and build tooling', 'SSR, code splitting, route generation, and build plugins.', contains('code-splitting', 'router-core-ssr', 'router-plugin', 'virtual-file-routes')),
      theme('framework-solid', 'Solid adapter', 'Solid Router adapter guidance.', exact('tanstack-solid-router')),
      theme('framework-vue', 'Vue adapter', 'Vue Router adapter guidance.', exact('tanstack-vue-router')),
    ],
    frameworks: [
      ['react', '@tanstack/react-router'],
      ['solid', '@tanstack/solid-router'],
      ['vue', '@tanstack/vue-router'],
    ],
    frameworkThemeMap: { react: 'foundations' },
    related: ['tanstack-start', 'tanstack-query'],
  }),
  product('query', 'TanStack Query', 'Server-state guidance for queries, mutations, caching, optimistic updates, SSR, persistence, testing, and all official adapters.', {
    maturity: 'Start with release-matched adapter documentation. Query Intent draft guidance is preserved separately and must be checked against the installed version.',
    docSupplement: true,
    atomicMatch: (name) => name.startsWith(queryPrefix),
    themes: [
      ...['react', 'preact', 'vue', 'solid', 'svelte', 'angular', 'lit'].map((framework) =>
        theme(`framework-${framework}`, `${titleCase(framework)} adapter`, `Release-matched ${titleCase(framework)} setup, queries, and reactivity.`, (_name, source) => source.kind === 'document' && source.frameworks.includes(framework))),
      theme('foundations', 'Foundations', 'Client setup, keys, options, fetching, defaults, and abstractions.', contains('setup-query-client', 'design-query-keys', 'fetch-and-observe', 'coordinate-query-execution', 'tune-defaults', 'understand-query-internals', 'build-query-abstractions')),
      theme('mutations', 'Mutations and cache updates', 'Mutations, invalidation, cancellation, and optimistic updates.', contains('write-mutations', 'cancel-queries', 'optimistic-updates', 'automatic-invalidati')),
      theme('data-shaping', 'Data shaping', 'Pagination, infinite queries, placeholders, selectors, and render efficiency.', contains('paginate-and-build', 'seed-placeholder', 'selectors-and-derived', 'shape-data-and-render')),
      theme('frameworks-ui', 'Frameworks and UI state', 'Adapter reactivity, status, errors, suspense, and devtools.', contains('use-framework-adapter', 'handle-status-and-errors', 'use-suspense', 'debug-with-devtools')),
      theme('routing-ssr', 'Routing and SSR', 'Router composition, prefetching, hydration, and streaming.', contains('compose-query-with', 'prefetch-and-remove', 'ssr-hydration')),
      theme('offline-integrations', 'Offline and integrations', 'Persistence, broadcast, realtime, and form integration.', contains('persist-offline', 'broadcast-realtime', 'query-data-and-forms')),
      theme('quality', 'Quality and migration', 'Lint rules, tests, and major-version migration.', contains('enforce-query', 'migrate-major', 'test-query')),
    ],
    frameworks: [
      ['react', '@tanstack/react-query'],
      ['preact', '@tanstack/preact-query'],
      ['vue', '@tanstack/vue-query'],
      ['solid', '@tanstack/solid-query'],
      ['svelte', '@tanstack/svelte-query'],
      ['angular', '@tanstack/angular-query-experimental'],
      ['lit', '@tanstack/lit-query'],
    ],
    frameworkNote: 'Adapter versions are listed on their guides. In particular, Svelte and Lit may use different major versions from Query Core. Draft task examples are not evidence that an API exists in another adapter.',
    tasks: [
      ['React: optimistic updates and rollback', 'docs/framework/react/guides/optimistic-updates.md'],
      ['Vue: refetch when reactive inputs change', 'docs/framework/vue/reactivity.md'],
    ],
    related: ['tanstack-router', 'tanstack-start', 'tanstack-form'],
  }),
  product('table', 'TanStack Table', 'Headless table and data-grid guidance with shared Table Core features and framework-specific adapters.', {
    atomicMatch: (name) =>
      /^tanstack-table-core(?:-|$)/.test(name) ||
      name === 'tanstack-table-devtools' ||
      name === 'tanstack-match-sorter-utils-fuzzy-ranking' ||
      tableAdapters.some((adapter) => new RegExp(`^tanstack-${adapter}-table(?:-|$)`).test(name)),
    themes: [
      theme('foundations', 'Foundations', 'Table Core, feature composition, and TypeScript.', exact('tanstack-table-core', 'tanstack-table-core-table-features', 'tanstack-table-core-typescript')),
      theme('data-processing', 'Data processing', 'Sorting, filtering, faceting, grouping, aggregation, pagination, and client/server boundaries.', contains('client-vs-server', 'sorting', 'column-filtering', 'global-filtering', 'column-faceting', 'grouping', 'aggregation', 'pagination')),
      theme('layout-interaction', 'Layout and interaction', 'Ordering, pinning, sizing, visibility, selection, spanning, and expanding.', contains('column-ordering', 'column-pinning', 'column-sizing', 'column-resizing', 'column-visibility', 'row-pinning', 'row-selection', 'cell-selection', 'cell-spanning', 'expanding')),
      theme('integrations', 'Integrations and tools', 'Devtools and fuzzy ranking.', exact('tanstack-table-devtools', 'tanstack-match-sorter-utils-fuzzy-ranking')),
      theme('advanced', 'Advanced and migration', 'Custom features, API diagnostics, and migration.', contains('api-not-found', 'custom-features', 'table-core-migrate')),
      ...tableAdapters.map((adapter) =>
        theme(`framework-${adapter}`, `${titleCase(adapter)} adapter`, `${titleCase(adapter)} Table adapter guidance.`, (name) =>
          new RegExp(`^tanstack-${adapter}-table(?:-|$)`).test(name))),
    ],
    frameworks: tableAdapters.map((adapter) => [adapter, `@tanstack/${adapter}-table`]),
    related: ['tanstack-query', 'tanstack-virtual'],
  }),
  product('charts', 'TanStack Charts', 'Typed chart grammar guidance for marks, scales, layouts, interaction, accessibility, rendering, and framework adapters.', {
    maturity: 'TanStack Charts 0.x is pre-alpha. Use only the API documented for the recorded release.',
    atomicMatch: () => false,
    docOnly: true,
    themes: docThemes('charts'),
    related: [],
  }),
  product('form', 'TanStack Form', 'Type-safe form guidance for fields, validation, composition, submission, SSR, devtools, and framework adapters.', {
    atomicMatch: () => false,
    docOnly: true,
    themes: docThemes('form'),
    tasks: [['React: field validation and submission', 'docs/framework/react/guides/validation.md']],
    related: ['tanstack-start', 'tanstack-devtools'],
  }),
  product('db', 'TanStack DB', 'Reactive collection guidance for live queries, optimistic mutations, persistence, sync engines, and framework adapters.', {
    maturity: 'TanStack DB is beta. Confirm package versions before using adapter or sync APIs.',
    atomicMatch: (name) =>
      /^tanstack-db-(?:core|meta-framework|playbook|skills)(?:-|$)/.test(name) ||
      /^tanstack-(?:react|vue|solid|svelte|angular)-db$/.test(name) ||
      /^tanstack-offline-transactions(?:-|$)/.test(name),
    themes: [
      theme('foundations', 'Foundations', 'DB architecture and meta-framework routing.', (name) =>
        exact('tanstack-db-core', 'tanstack-db-meta-framework', 'tanstack-db-playbook-tanstack-db', 'tanstack-db-skills-tanstack-db')(name)),
      theme('collections-schema', 'Collections and schemas', 'Collection setup, collection types, and schemas.', contains('collection-setup', 'tanstack-db-collections', 'tanstack-db-schemas')),
      theme('live-queries', 'Live queries', 'Reactive live-query construction and operators.', contains('live-queries')),
      theme('mutations', 'Mutations', 'Optimistic mutation and transaction patterns.', contains('mutations')),
      theme('sync-persistence', 'Sync and persistence', 'Persistence, custom adapters, offline transactions, and Electric.', contains('custom-adapter', 'persistence', 'offline-transactions', 'tanstack-db-electric')),
      ...dbAdapters.map((adapter) => theme(`framework-${adapter}`, `${titleCase(adapter)} adapter`, `${titleCase(adapter)} DB adapter guidance.`, exact(`tanstack-${adapter}-db`))),
    ],
    frameworks: dbAdapters.map((adapter) => [adapter, `@tanstack/${adapter}-db`]),
    related: ['tanstack-query', 'tanstack-start'],
  }),
  product('ai', 'TanStack AI', 'Provider-agnostic AI guidance for chat, tools, structured output, persistence, memory, runtime skills, MCP, code mode, and sandbox execution.', {
    maturity: 'TanStack AI is beta. Confirm provider and adapter package versions.',
    atomicMatch: (name) => /^tanstack-ai(?:-|$)/.test(name),
    themes: [
      theme('chat-providers', 'Chat, providers, and streaming', 'Core chat, providers, AG-UI, custom backends, and debugging.', (name) =>
        name === 'tanstack-ai-core' || contains('adapter-configuration', 'ag-ui', 'chat-experience', 'custom-backend-integration', 'debug-logging')(name)),
      theme('tools-outputs-middleware', 'Tools, outputs, and middleware', 'Tool calling, structured output, and middleware.', contains('tool-calling', 'structured-outputs', 'core-middleware')),
      theme('media', 'Media generation', 'Media generation guidance.', contains('media-generation')),
      theme('persistence-coordination', 'Persistence and coordination', 'Client/server persistence, stores, and locks.', (name) =>
        contains('client-persistence', 'core-locks', 'ai-persistence-server', 'ai-persistence-stores')(name) || name === 'tanstack-ai-persistence'),
      theme('persistence-adapters', 'Database persistence adapters', 'Custom, Drizzle, and Prisma persistence adapters.', contains('persistence-build-custom', 'persistence-build-drizzle', 'persistence-build-prisma')),
      theme('persistence-cloudflare', 'Cloudflare persistence', 'Cloudflare state and artifact-store persistence adapters.', contains('persistence-build-cloudflare')),
      theme('memory', 'Memory', 'Memory architecture and memory-provider adapters.', contains('ai-memory')),
      theme('agent-runtimes', 'Agent runtimes', 'Portable Agent Skills and MCP integration.', exact('tanstack-ai-skills', 'tanstack-ai-mcp')),
      theme('code-execution', 'Code execution', 'Code Mode and sandbox execution.', exact('tanstack-ai-code-mode', 'tanstack-ai-sandbox')),
    ],
    frameworks: [
      ['vanilla', '@tanstack/ai'],
      ['react', '@tanstack/ai-react'],
      ['preact', '@tanstack/ai-preact'],
      ['vue', '@tanstack/ai-vue'],
      ['solid', '@tanstack/ai-solid'],
      ['svelte', '@tanstack/ai-svelte'],
      ['angular', '@tanstack/ai-angular'],
    ],
    frameworkNote: 'The extracted upstream skills focus on core/server behavior. Confirm client adapter APIs from the installed package types.',
    related: [],
  }),
  product('intent', 'TanStack Intent', 'Guidance for discovering, installing, generating, validating, and maintaining package-owned Agent Skills.', {
    maturity: 'TanStack Intent is alpha. Confirm the CLI version before using generated configuration.',
    atomicMatch: () => false,
    docOnly: true,
    themes: docThemes('intent'),
    related: ['tanstack-cli'],
  }),
  product('virtual', 'TanStack Virtual', 'Virtualization guidance for large lists, grids, dynamic measurement, reverse feeds, and framework adapters.', {
    atomicMatch: () => false,
    docOnly: true,
    themes: docThemes('virtual'),
    related: ['tanstack-table'],
  }),
  product('pacer', 'TanStack Pacer', 'Execution-control guidance for debounce, throttle, rate limit, queue, batch, async retry, and framework adapters.', {
    maturity: 'TanStack Pacer is beta. Confirm utility and adapter versions.',
    atomicMatch: () => false,
    docOnly: true,
    themes: docThemes('pacer'),
    related: ['tanstack-devtools'],
  }),
  product('hotkeys', 'TanStack Hotkeys', 'Type-safe keyboard shortcut guidance for registration, sequences, scopes, recording, key state, display, and adapters.', {
    maturity: 'TanStack Hotkeys is alpha. Confirm behavior across target keyboard layouts and operating systems.',
    atomicMatch: () => false,
    docOnly: true,
    themes: docThemes('hotkeys'),
    related: ['tanstack-devtools'],
  }),
  product('markdown', 'TanStack Markdown', 'Markdown parsing, extensions, rendering, production pipeline, and framework-adapter guidance.', {
    maturity: 'TanStack Markdown is alpha. Confirm parser and renderer versions.',
    atomicMatch: (name) => /^tanstack-markdown(?:-|$)/.test(name),
    themes: [
      theme('parsing-extensions', 'Parsing and extensions', 'Markdown parsing, documentation features, and extensions.', contains('render-markdown', 'docs-features', 'custom-extensions')),
      theme('production', 'Production pipelines', 'Production parsing and rendering pipelines.', contains('production-pipelines')),
      theme('framework-react', 'React renderer', 'React rendering guidance.', contains('react-rendering')),
      theme('framework-octane', 'Octane renderer', 'Octane rendering guidance.', contains('octane-rendering')),
    ],
    frameworks: [['react', '@tanstack/markdown/react'], ['octane', '@tanstack/markdown/octane']],
    related: ['tanstack-highlight'],
  }),
  product('highlight', 'TanStack Highlight', 'Syntax-highlighting guidance for language support, selective loading, Markdown pipelines, themes, and annotations.', {
    maturity: 'TanStack Highlight is alpha. Confirm the installed package version.',
    atomicMatch: (name) => /^tanstack-highlight(?:-|$)/.test(name),
    themes: [
      theme('languages-configuration', 'Languages and configuration', 'Selective highlighting and language extension.', contains('selective-highlighting', 'language-support')),
      theme('integrations', 'Framework and Markdown integration', 'Framework code blocks and Markdown pipelines.', contains('framework-code-blocks', 'markdown-pipelines')),
      theme('themes-annotations', 'Themes and annotations', 'Themes, styling, and annotations.', contains('theme-and-annotate')),
    ],
    frameworks: [['vanilla', '@tanstack/highlight'], ['react', '@tanstack/highlight/react']],
    frameworkThemeMap: { vanilla: 'languages-configuration', react: 'integrations' },
    related: ['tanstack-markdown'],
  }),
  product('store', 'TanStack Store', 'Reactive store guidance for state, atoms, selectors, batching, async state, and framework adapters.', {
    maturity: 'TanStack Store is alpha. Confirm core and adapter versions.',
    atomicMatch: () => false,
    docOnly: true,
    themes: docThemes('store'),
    related: [],
  }),
  product('config', 'TanStack Config', 'Library-maintenance guidance for package structure, dependencies, ESLint, Vite, publishing, and CI/CD.', {
    atomicMatch: () => false,
    docOnly: true,
    themes: docThemes('config'),
    related: [],
  }),
  product('devtools', 'TanStack Devtools', 'Devtools guidance for setup, framework adapters, plugins, event instrumentation, marketplace use, and production builds.', {
    maturity: 'TanStack Devtools is alpha. Confirm core and plugin versions.',
    atomicMatch: (name) => /^tanstack-devtools(?:-|$)/.test(name),
    themes: [
      theme('setup-production', 'Setup and production', 'App setup, Vite integration, and production behavior.', contains('app-setup', 'vite-plugin', 'production')),
      theme('plugins-marketplace', 'Plugins and marketplace', 'Plugin panels, framework adapters, and marketplace use.', contains('plugin-panel', 'framework-adapters', 'marketplace')),
      theme('events-instrumentation', 'Events and instrumentation', 'Event client, instrumentation, and bidirectional events.', contains('event-client')),
    ],
    frameworks: [
      ['vanilla', '@tanstack/devtools'],
      ['react', '@tanstack/react-devtools'],
      ['preact', '@tanstack/preact-devtools'],
      ['solid', '@tanstack/solid-devtools'],
      ['vue', '@tanstack/vue-devtools'],
      ['svelte', '@tanstack/svelte-devtools'],
      ['angular', '@tanstack/angular-devtools'],
    ],
    frameworkDefaultTheme: 'plugins-marketplace',
    related: [],
  }),
  product('cli', 'TanStack CLI', 'Project scaffolding and maintenance guidance for app creation, add-ons, ecosystem integration, custom development, and documentation queries.', {
    maturity: 'TanStack CLI is alpha. Confirm the installed CLI version and command help.',
    atomicMatch: (name) => /^tanstack-cli(?:-|$)/.test(name),
    themes: [
      theme('projects-addons', 'Projects and add-ons', 'Create applications and add add-ons.', contains('create-app-scaffold', 'add-addons')),
      theme('ecosystem-discovery', 'Ecosystem and discovery', 'Choose integrations and query library metadata.', contains('ecosystem-integrations', 'query-docs')),
      theme('addon-authoring', 'Add-on authoring', 'Develop and watch custom add-ons.', contains('custom-addons')),
    ],
    related: ['tanstack-intent'],
  }),
]

function docThemes(id) {
  const frameworks = (docFrameworks[id] || []).map((framework) =>
    theme(`framework-${framework}`, `${titleCase(framework)} adapter`, `${titleCase(framework)}-specific setup and behavior.`, (_name, source) => source.frameworks.includes(framework)))
  if (id === 'charts') return [
    theme('getting-started', 'Getting started', 'Overview, comparison, installation, and quick start.', (_name, source) => /^(?:comparison|installation|overview|quick-start)\.md$/.test(source.outputPath)),
    theme('chart-grammar', 'Chart grammar', 'Chart concepts, chart selection, and TypeScript guidance.', (_name, source) => /^(?:concepts\/[^/]+|guides\/(?:choosing-a-chart|typescript))\.md$/.test(source.outputPath)),
    theme('examples-core', 'Core visualization patterns', 'Common annotations, bars, distributions, heatmaps, intervals, lines, scatterplots, and stacking.', (_name, source) => /^examples\/(?:annotations-and-overlays|bars-and-rankings|distributions|heatmaps-and-densities|index|intervals-and-financial|lines-and-areas|scatterplots-and-relationships|stacked-and-composition)\.md$/.test(source.outputPath)),
    theme('examples-advanced', 'Advanced visualization patterns', 'Facets, interaction, maps, networks, polar charts, themes, and motion.', (_name, source) => /^examples\/(?:facets-and-multiple-views|interactive-charts|maps-and-spatial|networks-and-hierarchies|polar-and-radar|themes-and-motion)\.md$/.test(source.outputPath)),
    theme('marks-cartesian-statistical', 'Cartesian and statistical marks', 'Cartesian, distribution, density, regression, and statistical mark reference.', (_name, source) => /^reference\/marks\/(?:bar-and-rect|box|contour|density|difference|dodge|dot-and-hexagon|hexbin|line-and-area|regression|ridgeline|violin)\.md$/.test(source.outputPath)),
    theme('marks-spatial', 'Spatial and polar marks', 'Spatial, polar, focus-guide, Delaunay, geo, and Voronoi mark reference.', (_name, source) => /^reference\/marks\/(?:delaunay|focus-guide|geo|polar|voronoi)\.md$/.test(source.outputPath)),
    theme('marks-composite', 'Composite and hierarchy marks', 'Composite, network, hierarchy, rule, frame, and waffle mark reference.', (_name, source) => /^reference\/marks\/(?:rules-links-arrows-vectors-and-ticks|sankey|sunburst|text-frame-and-facet|treemap|waffle)\.md$/.test(source.outputPath)),
    theme('specifications', 'Specifications', 'Chart definitions, specifications, and reference index.', (_name, source) => /^reference\/(?:chart-definitions|chart-spec|index)\.md$/.test(source.outputPath)),
    theme('types', 'Type reference', 'Chart TypeScript definitions and type reference.', (_name, source) => source.outputPath === 'reference/types.md'),
    theme('interaction-motion-reference', 'Interaction and motion reference', 'Focus, interaction, and motion reference.', (_name, source) => /^reference\/(?:focus-and-interaction|motion)\.md$/.test(source.outputPath)),
    theme('runtime-scales-reference', 'Runtime and scales reference', 'Runtime, scene, scales, guides, and color reference.', (_name, source) => /^reference\/(?:runtime-and-scene|scales-guides-and-color)\.md$/.test(source.outputPath)),
    theme('rendering-composition-reference', 'Rendering and composition reference', 'Adapters, extensions, hosts, rendering, export, transforms, and view composition.', (_name, source) => /^reference\/(?:adapter-controller|custom-extensions|dom-host|rendering-and-export|transforms|view-composition)\.md$/.test(source.outputPath)),
    theme('composition', 'Composition and customization', 'Composition, custom marks, renderers, transforms, colors, and animation.', (_name, source) => /(?:custom|faceting|legends|transforms|dynamic-data|themes-and-styling)/.test(source.outputPath)),
    theme('interaction-accessibility', 'Interaction and accessibility', 'Focus, tooltips, interaction, selection, and accessibility.', (_name, source) => /(?:interaction|selection|tooltip|focus|accessibility)/.test(source.outputPath)),
    theme('production', 'Production and migration', 'Responsive layout, performance, SSR, testing, export, authoring, and migration.', (_name, source) => /(?:responsive|performance|ssr|testing|export|ai-authoring|migrating|large-data)/.test(source.outputPath)),
    ...frameworks,
    theme('other-guides', 'Other official guides', 'Official guidance not covered by a narrower topic.', () => true),
  ]
  if (id === 'form') return [
    theme('foundations', 'Foundations', 'Overview, installation, philosophy, TypeScript, and comparison.', (_name, source) => source.frameworks.length === 0),
    theme('framework-react', 'React adapter', 'React quick start, fields, state, validation, submission, and reactivity.', (_name, source) => /^framework\/react\/(?:quick-start|guides\/(?:arrays|async-initial-values|basic-concepts|linked-fields|listeners|reactivity|submission-handling|validation))\.md$/.test(source.outputPath)),
    theme('framework-react-advanced', 'React advanced patterns', 'Advanced React composition, validation, SSR, and form architecture.', (_name, source) => source.frameworks.includes('react') && /^framework\/react\//.test(source.outputPath)),
    theme('framework-preact', 'Preact adapter', 'Preact quick start, fields, state, validation, submission, and reactivity.', (_name, source) => /^framework\/preact\/(?:quick-start|guides\/(?:arrays|async-initial-values|basic-concepts|linked-fields|listeners|reactivity|submission-handling|validation))\.md$/.test(source.outputPath)),
    theme('framework-preact-advanced', 'Preact advanced patterns', 'Advanced Preact composition, validation, debugging, focus, and UI integration.', (_name, source) => source.frameworks.includes('preact') && /^framework\/preact\//.test(source.outputPath)),
    ...frameworks.filter((entry) => !['framework-react', 'framework-preact'].includes(entry.key)),
  ]
  if (id === 'intent') return [
    theme('consumer-workflow', 'Consumer workflow', 'Install, list, load, and use skills.', (_name, source) => /(?:quick-start-consumers|cli\/intent-(?:install|list|load|exclude))/.test(source.outputPath)),
    theme('maintainer-workflow', 'Maintainer workflow', 'Set up, scaffold, validate, and maintain skills.', (_name, source) => /(?:quick-start-maintainers|cli\/intent-(?:setup|scaffold|validate|stale|hooks|meta))/.test(source.outputPath)),
    theme('trust-configuration', 'Trust, configuration, and registry', 'Trust boundaries, configuration, registry, and overview.', (_name, source) => /(?:concepts|registry|overview)/.test(source.outputPath)),
    theme('meta-discovery-generation', 'Meta discovery and generation', 'Official Intent meta skills for domain discovery and skill generation.', (_name, source) => source.document?.kind === 'meta-skill' && /\/(?:domain-discovery|generate-skill)\/SKILL\.md$/.test(source.sourcePath)),
    theme('meta-tree-maintenance', 'Meta trees and maintenance', 'Official Intent meta skills for tree generation and staleness checks.', (_name, source) => source.document?.kind === 'meta-skill' && /\/(?:tree-generator|skill-staleness-check)\/SKILL\.md$/.test(source.sourcePath)),
    theme('other-guides', 'Other official guides', 'Other official Intent guidance.', () => true),
  ]
  if (id === 'virtual') return [
    theme('foundations', 'Foundations', 'Introduction, installation, and Virtualizer APIs.', (_name, source) => source.frameworks.length === 0 && !/(?:chat|pretext)/.test(source.outputPath)),
    theme('measurement-feeds', 'Measurement and reverse feeds', 'Measurement and chat/reverse-feed virtualization.', (_name, source) => /(?:chat|pretext)/.test(source.outputPath)),
    ...frameworks,
  ]
  if (id === 'pacer') return [
    theme('foundations', 'Foundations and selection', 'Installation, quick start, overview, devtools, and utility selection.', (_name, source) => source.frameworks.length === 0 && (!source.outputPath.startsWith('guides/') || /which-pacer-utility/.test(source.outputPath))),
    theme('debounce-throttle', 'Debounce and throttle', 'Synchronous and asynchronous debounce/throttle.', (_name, source) => /(?:debounc|throttl)/.test(source.outputPath)),
    theme('queue-batch', 'Queue and batch', 'Synchronous and asynchronous queueing and batching.', (_name, source) => /(?:queu|batch)/.test(source.outputPath)),
    theme('rate-limiting', 'Rate limiting', 'Synchronous, asynchronous, and server-side rate limiting.', (_name, source) => /rate-limit/.test(source.outputPath)),
    theme('async-retry', 'Async and retry', 'Async execution and retry behavior.', (_name, source) => /(?:async|retry)/.test(source.outputPath)),
    ...frameworks,
    theme('other-guides', 'Other official guides', 'Other official Pacer guidance.', () => true),
  ]
  if (id === 'hotkeys') return [
    theme('foundations', 'Foundations', 'Overview, installation, and devtools.', (_name, source) => source.frameworks.length === 0 && !source.outputPath.startsWith('guides/')),
    theme('registration-sequences', 'Registration and sequences', 'Hotkey registration, parsing, sequences, scopes, and conflicts.', (_name, source) => source.frameworks.length === 0 && /(?:hotkey|sequence|scope|conflict|registration)/.test(source.outputPath)),
    theme('recording-state-display', 'Recording, state, and display', 'Recording shortcuts, key state, and platform-aware display.', (_name, source) => source.frameworks.length === 0 && /(?:record|held|key-state|display|format)/.test(source.outputPath)),
    ...frameworks,
    theme('other-guides', 'Other official guides', 'Other official Hotkeys guidance.', () => true),
  ]
  if (id === 'store') return [
    theme('foundations', 'Foundations', 'Core Store, atoms, selectors, batching, and async state.', (_name, source) => source.frameworks.length === 0),
    ...frameworks,
  ]
  if (id === 'config') return [
    theme('package-structure', 'Package structure and dependencies', 'Package organization and dependency policy.', (_name, source) => /(?:overview|package-structure|dependencies)/.test(source.outputPath)),
    theme('toolchain', 'ESLint and Vite', 'Lint and build configuration.', (_name, source) => /(?:eslint|vite)/.test(source.outputPath)),
    theme('publishing-ci', 'Publishing and CI/CD', 'Publishing and continuous delivery.', (_name, source) => /(?:publish|ci-cd)/.test(source.outputPath)),
  ]
  throw new Error(`No documentation themes for ${id}`)
}

function titleCase(value) {
  return value
    .split(/[-_/]+/)
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join(' ')
}

function sha256(value) {
  return createHash('sha256').update(value).digest('hex')
}

function normalizeText(value) {
  const text = value.replace(/\r\n?/g, '\n').replace(/[ \t]+$/gm, '')
  return `${text.replace(/\s+$/, '')}\n`
}

function json(value) {
  return `${JSON.stringify(value, null, 2)}\n`
}

async function exists(path) {
  try {
    await lstat(path)
    return true
  } catch (error) {
    if (error?.code === 'ENOENT') return false
    throw error
  }
}

async function walk(path) {
  const entries = (await readdir(path, { withFileTypes: true })).sort((a, b) => ascii(a.name, b.name))
  const files = []
  for (const entry of entries) {
    const child = join(path, entry.name)
    if (entry.isDirectory()) files.push(...(await walk(child)))
    else if (entry.isFile()) files.push(child)
    else throw new Error(`unsupported filesystem entry: ${child}`)
  }
  return files
}

function decodeYamlScalar(raw) {
  const value = raw.trim()
  if (value.startsWith('"')) return JSON.parse(value)
  if (value.startsWith("'")) return value.slice(1, -1).replace(/''/g, "'")
  return value
}

function parseFrontmatter(text, path) {
  const match = text.match(/^---\r?\n([\s\S]*?)\r?\n---(?:\r?\n|$)/)
  if (!match) throw new Error(`missing frontmatter: ${path}`)
  const fields = new Map()
  const metadata = new Map()
  let inMetadata = false
  for (const line of match[1].split(/\r?\n/)) {
    if (line === 'metadata:') {
      inMetadata = true
      continue
    }
    const field = line.match(inMetadata ? /^  ([a-z0-9-]+):\s*(.*)$/ : /^([a-z0-9-]+):\s*(.*)$/)
    if (!field) continue
    ;(inMetadata ? metadata : fields).set(field[1], decodeYamlScalar(field[2]))
  }
  const name = fields.get('name')
  const description = fields.get('description')
  if (!name || !description) throw new Error(`missing name or description: ${path}`)
  return {
    name,
    description,
    license: fields.get('license') || '',
    metadata,
    body: normalizeText(text.slice(match[0].length)),
  }
}

function readExportedNames(text) {
  const names = []
  for (const line of text.split(/\r?\n/)) {
    if (!line || line.startsWith('#') || line.startsWith('package\t')) continue
    const fields = line.split('\t')
    if (fields.length !== 6) throw new Error(`invalid exporter manifest row: ${line}`)
    for (const name of fields[5].split(',').filter(Boolean)) names.push(name)
  }
  if (!names.length || new Set(names).size !== names.length) {
    throw new Error('exporter manifest has no skills or duplicate output names')
  }
  return names.sort(ascii)
}

async function readAtomicSkills(docPackageOwners) {
  const names = readExportedNames(await readFile(exportManifestPath, 'utf8'))
  const skills = []
  for (const name of names) {
    const directory = join(skillsDir, name)
    const skillPath = join(directory, 'SKILL.md')
    const text = await readFile(skillPath, 'utf8')
    const parsed = parseFrontmatter(text, skillPath)
    if (parsed.name !== name) throw new Error(`atomic skill name does not match directory: ${skillPath}`)
    const packageName = parsed.metadata.get('tanstack-package')
    const productSpec = resolveProduct(
      productSpecs,
      {
        id: name,
        name,
        packageName,
        libraryName: parsed.metadata.get('tanstack-library'),
      },
      docPackageOwners,
    )
    skills.push({
      kind: 'atomic',
      id: name,
      name,
      directory,
      skillPath,
      text,
      body: parsed.body,
      description: parsed.description,
      license: parsed.license,
      metadata: parsed.metadata,
      productId: productSpec.id,
      supplemental: false,
      frameworks: [],
      outputPath: '',
      sourcePath: parsed.metadata.get('tanstack-source-skill') || name,
      packageName: parsed.metadata.get('tanstack-package') || '',
      packageVersion: parsed.metadata.get('tanstack-package-version') || '',
      sourceRef: parsed.metadata.get('tanstack-source-ref') || '',
      sourceDocuments: parseJsonArray(parsed.metadata.get('tanstack-sources'), `tanstack-sources for ${name}`),
      sha256: sha256(Buffer.from(normalizeText(text.replace(/^  internal:\s*true\s*\n/m, '')))),
    })
  }
  return skills
}

function validateDocManifest(manifest) {
  if (manifest?.schemaVersion !== 1 || manifest?.generator !== 'scripts/fetch-doc-sources.mjs') {
    throw new Error('invalid documentation source manifest')
  }
  if (JSON.stringify(manifest.catalog?.ids) !== JSON.stringify(expectedCatalogIds)) {
    throw new Error('documentation source catalog does not match the expected public catalog')
  }
  const ids = manifest.products?.map((entry) => entry.id)
  const expected = productSpecs.filter((spec) => spec.docOnly || spec.docSupplement).map((spec) => spec.id).sort(ascii)
  if (!Array.isArray(ids) || JSON.stringify([...ids].sort(ascii)) !== JSON.stringify(expected)) {
    throw new Error(`documentation source products must be exactly: ${expected.join(', ')}`)
  }
}

async function readDocSources() {
  const manifestPath = join(docSourceDir, 'manifest.json')
  const manifest = JSON.parse(await readFile(manifestPath, 'utf8'))
  validateDocManifest(manifest)
  const docPackageOwners = new Map()
  for (const productManifest of manifest.products) {
    const packageNames = new Set([
      productManifest.sourcePackage,
      ...productManifest.releasePackages.map((entry) => entry.name),
    ])
    for (const packageName of packageNames) {
      const previousOwner = docPackageOwners.get(packageName)
      if (previousOwner && previousOwner !== productManifest.id) {
        throw new Error(`documentation package ${packageName} belongs to both ${previousOwner} and ${productManifest.id}`)
      }
      docPackageOwners.set(packageName, productManifest.id)
    }
  }
  const byProduct = new Map()
  for (const productManifest of manifest.products) {
    const productRoot = join(docSourceDir, 'products', productManifest.id)
    const sources = []
    for (const document of productManifest.documents) {
      const file = join(productRoot, ...document.sourcePath.split('/'))
      const bytes = await readFile(file)
      if (sha256(bytes) !== document.sha256) {
        throw new Error(`documentation hash mismatch: ${document.sourcePath}`)
      }
      const text = normalizeText(bytes.toString('utf8'))
      sources.push({
        kind: 'document',
        id: `${productManifest.id}:${document.sourcePath}`,
        name: document.sourcePath,
        directory: productRoot,
        file,
        body: stripDocumentFrontmatter(text),
        description: '',
        license: 'MIT',
        productId: productManifest.id,
        supplemental: false,
        frameworks: document.frameworks || [],
        outputPath: document.outputPath,
        sourcePath: document.sourcePath,
        packageName: document.sourcePackage || productManifest.sourcePackage,
        packageVersion: productManifest.releasePackages.find((entry) => entry.name === (document.sourcePackage || productManifest.sourcePackage))?.version || '',
        sourceCommit: document.sourceCommit || productManifest.commit,
        sourceRef: `github:${productManifest.repository}@${document.sourceCommit || productManifest.commit}#${document.sourcePath}`,
        sha256: document.sha256,
        document,
        productManifest,
      })
    }
    byProduct.set(productManifest.id, { manifest: productManifest, sources, productRoot })
  }
  return { manifest, byProduct, docPackageOwners }
}

function stripDocumentFrontmatter(text) {
  const match = text.match(/^---\n[\s\S]*?\n---(?:\n|$)/)
  return normalizeText(match ? text.slice(match[0].length) : text)
}

function parseJsonArray(value, label) {
  if (!value) return []
  let parsed
  try {
    parsed = JSON.parse(value)
  } catch {
    throw new Error(`${label} is not valid JSON`)
  }
  if (!Array.isArray(parsed) || parsed.some((entry) => typeof entry !== 'string')) {
    throw new Error(`${label} must be an array of strings`)
  }
  return parsed
}

function sourcePriority(source) {
  if (source.kind === 'document') return 50
  if (source.packageName === '@tanstack/db') return 0
  if (source.packageName === '@tanstack/db-playbook') return 10
  if (source.packageName === '@tanstack/db-skills') return 20
  return 5
}

function splitH2(body) {
  const lines = normalizeText(body).trimEnd().split('\n')
  if (lines[0]?.startsWith('# ') && !lines[0].startsWith('## ')) {
    lines.shift()
    while (lines[0] === '') lines.shift()
  }
  const blocks = []
  let heading = 'Overview'
  let content = []
  let fence = null
  const flush = () => {
    const value = normalizeText(content.join('\n')).trim()
    if (value) blocks.push({ heading, content: `${value}\n` })
    content = []
  }
  for (const line of lines) {
    const fenceMatch = line.match(/^\s*(```+|~~~+)/)
    if (fenceMatch) {
      const marker = fenceMatch[1]
      if (!fence) fence = { character: marker[0], length: marker.length }
      else if (fence.character === marker[0] && marker.length >= fence.length) fence = null
      content.push(line)
      continue
    }
    const h2 = !fence && line.match(/^##\s+(.+?)\s*$/)
    if (h2) {
      flush()
      heading = h2[1]
      continue
    }
    content.push(line)
  }
  flush()
  return blocks
}

function sourceLabel(source) {
  if (source.kind === 'document') {
    return titleCase(source.outputPath.replace(/\.(?:md|mdx)$/i, '').split('/').at(-1))
  }
  const candidate = source.sourcePath.split('/').at(-1) || source.name
  return titleCase(candidate)
}

function anchorFor(source) {
  return `source-${source.id.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')}`
}

function canonicalBlock(block) {
  return normalizeText(`${block.heading}\n${block.content}`)
    .replaceAll('./references/', 'references/')
    .replaceAll('../references/', 'references/')
}

async function collectAtomicAssetMap(spec, sources, outputDir) {
  const map = new Map()
  for (const source of sources.filter((entry) => entry.kind === 'atomic')) {
    const referenceDir = join(source.directory, 'references')
    if (!(await exists(referenceDir))) continue
    for (const file of await walk(referenceDir)) {
      const rel = relative(source.directory, file).split(sep).join('/')
      if (rel === 'references/INTENT-SKILL-MAP.md') continue
      const targetRel = `references/assets/${source.name}/${rel}`
      const target = join(outputDir, ...targetRel.split('/'))
      await mkdir(dirname(target), { recursive: true })
      await copyFile(file, target)
      map.set(resolve(file), targetRel)
    }
  }
  return map
}

async function collectDocAssetMap(docBundle, outputDir) {
  const map = new Map()
  if (!docBundle) return map
  for (const asset of docBundle.manifest.assets || []) {
    const source = join(docBundle.productRoot, ...asset.sourcePath.split('/'))
    const targetRel = `references/doc-assets/${asset.outputPath}`
    const target = join(outputDir, ...targetRel.split('/'))
    const bytes = await readFile(source)
    if (sha256(bytes) !== asset.sha256) throw new Error(`documentation asset hash mismatch: ${asset.sourcePath}`)
    await mkdir(dirname(target), { recursive: true })
    await writeFile(target, bytes)
    map.set(posix.normalize(asset.sourcePath), targetRel)
    map.set(posix.normalize(asset.outputPath), targetRel)
    map.set(posix.normalize(posix.join('docs', asset.outputPath)), targetRel)
  }
  return map
}

function rewriteLinks(text, context) {
  const rewriteLine = (line) => line.replace(/\]\(([^)]+)\)/g, (match, rawTarget, offset) => {
    if (isInsideInlineCode(line, offset)) return match
    const wrapped = rawTarget.trim()
    const targetValue = wrapped.startsWith('<') && wrapped.endsWith('>') ? wrapped.slice(1, -1) : wrapped
    const liveGithub = targetValue.match(/^https:\/\/github\.com\/([^/]+\/[^/]+)\/(?:blob|tree)\/(?:main|master)\/([^#?]+)([?#].*)?$/i)
    if (liveGithub && context.source.sourceDocuments?.includes(`${liveGithub[1]}:${liveGithub[2]}`)) {
      const output = context.sourceOutputMap.get(context.source.id)
      if (!output) throw new Error(`source document link has no bundled output: ${context.source.id}`)
      return `](${relativeLink(context.outputFile, output.file)}#${output.anchor})`
    }
    const pinned = pinMutableRepositoryRefs(targetValue, gitSource(context.source))
    if (pinned !== targetValue) return `](${pinned})`
    const parts = targetValue.match(/^([^#?]*)([?#].*)?$/)
    if (!parts) return match
    let target = parts[1]
    const suffix = parts[2] || ''
    if (!target && suffix.startsWith('#')) {
      const output = context.sourceOutputMap.get(context.source.id)
      return `](${relativeLink(context.outputFile, output.file)}${suffix})`
    }
    if (!target || /^(?:[a-z]+:|#)/i.test(target)) return match
    if (target.startsWith('/')) {
      return context.source.kind === 'document' ? `](https://tanstack.com${target}${suffix})` : match
    }
    try {
      target = decodeURIComponent(target)
    } catch {
      throw new Error(`invalid encoded link in ${context.source.id}: ${rawTarget}`)
    }

    if (context.source.kind === 'atomic') {
      const absolute = resolve(dirname(context.source.skillPath), target)
      const localAsset = context.atomicAssetMap.get(absolute)
      if (localAsset) return `](${relativeLink(context.outputFile, join(context.productDir, ...localAsset.split('/')))}${suffix})`
      const targetSource = resolveAtomicTarget(target, context)
      if (targetSource) return `](${atomicTargetDestination(targetSource, context)}${suffix.startsWith('#') ? '' : suffix})`
      if (/SKILL\.md$/i.test(target)) {
        const origin = context.atomicOriginById.get(context.source.id)
        const resolvedOrigin = origin && posix.normalize(posix.join(posix.dirname(origin), target))
        throw new Error(`unresolved atomic skill link in ${context.source.id}: ${target} (resolved ${resolvedOrigin || 'unknown'})`)
      }
      return match
    }

    const resolvedSourcePath = posix.normalize(posix.join(posix.dirname(context.source.sourcePath), target))
    const targetSource = context.docPathMap.get(resolvedSourcePath)
    if (targetSource && context.sourceOutputMap.has(targetSource.id)) {
      const output = context.sourceOutputMap.get(targetSource.id)
      return `](${relativeLink(context.outputFile, output.file)}#${output.anchor}${suffix.startsWith('#') ? '' : suffix})`
    }
    const localAsset = context.docAssetMap.get(resolvedSourcePath)
    if (localAsset) return `](${relativeLink(context.outputFile, join(context.productDir, ...localAsset.split('/')))}${suffix})`
    const repo = context.source.productManifest.repository
    const commit = context.source.sourceCommit || context.source.productManifest.commit
    return `](https://github.com/${repo}/blob/${commit}/${resolvedSourcePath}${suffix})`
  })
  let fence = null
  return text.split('\n').map((line) => {
    const fenceMatch = line.match(/^\s*(```+|~~~+)/)
    if (fenceMatch) {
      const marker = fenceMatch[1]
      if (!fence) fence = { character: marker[0], length: marker.length }
      else if (fence.character === marker[0] && marker.length >= fence.length) fence = null
      return line
    }
    return fence ? line : pinMutableRepositoryRefsInLine(rewriteAtomicLiteralSkillPaths(rewriteLine(line), context), context.source)
  }).join('\n')
}

function isInsideInlineCode(line, index) {
  let delimiterLength = 0
  for (const match of line.slice(0, index).matchAll(/`+/g)) {
    if (!delimiterLength) delimiterLength = match[0].length
    else if (match[0].length === delimiterLength) delimiterLength = 0
  }
  return delimiterLength > 0
}

function resolveAtomicTarget(target, context) {
  const absolute = resolve(dirname(context.source.skillPath), target)
  const direct = context.atomicFileMap.get(absolute)
  if (direct) return direct
  const origin = context.atomicOriginById.get(context.source.id)
  const resolvedOrigin = origin && posix.normalize(posix.join(posix.dirname(origin), target))
  const candidates = [
    resolvedOrigin,
    posix.normalize(target),
    posix.normalize(target.replace(/^node_modules\/@tanstack\//, 'packages/')),
  ].filter(Boolean)
  for (const candidate of candidates) {
    const source = context.atomicOriginMap.get(candidate)
    if (source) return source
  }
  return undefined
}

function atomicTargetDestination(targetSource, context) {
  const output = context.sourceOutputMap.get(targetSource.id)
  if (output) return `${relativeLink(context.outputFile, output.file)}#${output.anchor}`
  if (targetSource.productId === context.source.productId) {
    throw new Error(`in-product atomic link was not bundled: ${context.source.id} -> ${targetSource.id}`)
  }
  return `https://skills.sh/lukasa1993/tanstack-skills-extracted/tanstack-${targetSource.productId}`
}

function rewriteAtomicLiteralSkillPaths(line, context) {
  if (context.source.kind !== 'atomic') return line
  const pattern = /(?:node_modules\/@tanstack\/[a-z0-9_@.*\/-]+|(?:\.\.\/)+[a-z0-9_@.*\/-]+|(?:ai-persistence|compositions)\/[a-z0-9_@.*\/-]+)\/SKILL\.md/gi
  return line.replace(pattern, (target) => {
    if (target.includes('*') && context.source.productId === 'ai' && target.startsWith('ai-persistence/')) {
      return relativeLink(context.outputFile, join(context.productDir, 'references', 'persistence-adapters.md'))
    }
    const targetSource = resolveAtomicTarget(target, context)
    if (!targetSource) throw new Error(`unresolved literal atomic skill path in ${context.source.id}: ${target}`)
    return atomicTargetDestination(targetSource, context)
  })
}

function gitSource(source) {
  if (source.productManifest && source.sourceCommit) {
    return { repository: source.productManifest.repository, commit: source.sourceCommit }
  }
  const match = source.sourceRef?.match(/^github:([^@]+)@([0-9a-f]{40})#/i)
  return match ? { repository: match[1], commit: match[2] } : null
}

function pinMutableRepositoryRefs(value, sourceGit) {
  if (!sourceGit) return value
  const escapedRepo = sourceGit.repository.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  const patterns = [
    new RegExp(`(https://github\\.com/${escapedRepo}/(?:blob|tree)/)(?:main|master)(?=/|[?#]|$)`, 'gi'),
    new RegExp(`(https://raw\\.githubusercontent\\.com/${escapedRepo}/)(?:main|master)(?=/|[?#]|$)`, 'gi'),
    new RegExp(`(https://(?:codesandbox\\.io/s/|stackblitz\\.com/)github/${escapedRepo}/(?:blob|tree)/)(?:main|master)(?=/|[?#]|$)`, 'gi'),
  ]
  return patterns.reduce((result, pattern) => result.replace(pattern, `$1${sourceGit.commit}`), value)
}

function pinMutableRepositoryRefsInLine(line, source) {
  const sourceGit = gitSource(source)
  if (!sourceGit) return line
  return line.replace(/https:\/\/[^\s<>"'`)]+/gi, (url, offset) =>
    isInsideInlineCode(line, offset) ? url : pinMutableRepositoryRefs(url, sourceGit))
}

function containsMutableRepositoryRef(value) {
  return [
    /https:\/\/github\.com\/[^/\s]+\/[^/\s]+\/(?:blob|tree)\/(?:main|master)(?=\/|[?#]|$)/i,
    /https:\/\/raw\.githubusercontent\.com\/[^/\s]+\/[^/\s]+\/(?:main|master)(?=\/|[?#]|$)/i,
    /https:\/\/(?:codesandbox\.io\/s\/|stackblitz\.com\/)github\/[^/\s]+\/[^/\s]+\/(?:blob|tree)\/(?:main|master)(?=\/|[?#]|$)/i,
  ].some((pattern) => pattern.test(value))
}

function relativeLink(fromFile, toFile) {
  let value = relative(dirname(fromFile), toFile).split(sep).join('/')
  if (!value.startsWith('.')) value = `./${value}`
  return value
}

function documentationFrameworks(spec, docManifest) {
  if (!docManifest?.frameworks?.length && !docManifest?.experimentalFrameworks?.length) return []
  const corePackages = {
    charts: '@tanstack/charts',
    form: '@tanstack/form-core',
    hotkeys: '@tanstack/hotkeys',
    pacer: '@tanstack/pacer',
    store: '@tanstack/store',
    virtual: '@tanstack/virtual-core',
  }
  const experimental = new Set(docManifest.experimentalFrameworks || [])
  const frameworks = [...new Set([...(docManifest.frameworks || []), ...experimental])]
  return frameworks.map((framework) => {
    if (framework === 'vanilla') return [framework, corePackages[spec.id], false]
    if (spec.id === 'charts' && framework === 'react-native') {
      return [framework, '@tanstack/react-native-charts', experimental.has(framework)]
    }
    if (spec.id === 'charts') return [framework, `@tanstack/charts/${framework}`, experimental.has(framework)]
    return [framework, `@tanstack/${framework}-${spec.id}`, experimental.has(framework)]
  })
}

function frameworkReference(spec, themes, framework, foundationTheme) {
  const mappedKey = spec.frameworkThemeMap?.[framework] || spec.frameworkDefaultTheme
  return themes.find((entry) => entry.key === `framework-${framework}`)
    || (mappedKey ? themes.find((entry) => entry.key === mappedKey) : undefined)
    || themes.find((entry) => entry.key === 'frameworks' || entry.key === 'frameworks-ui')
    || (framework === 'vanilla' ? foundationTheme : undefined)
}

function buildRootSkill(spec, themes, sourceCount, docManifest, routes) {
  const frameworkRoutes = spec.frameworks || documentationFrameworks(spec, docManifest)
  const foundationTheme = themes.find((entry) => ['foundations', 'getting-started'].includes(entry.key))
  const hasFrameworkReference = frameworkRoutes.some(([framework]) => frameworkReference(spec, themes, framework, foundationTheme))
  let workflowStep2 = '2. Choose the task reference that matches the requested outcome.'
  if (foundationTheme && hasFrameworkReference) workflowStep2 = '2. Read the foundation reference and the adapter reference for the detected framework.'
  else if (foundationTheme) workflowStep2 = '2. Read the foundation reference before the task-specific reference.'
  else if (hasFrameworkReference) workflowStep2 = '2. Read the adapter reference for the detected framework when the task uses an adapter.'
  if (spec.id === 'query') workflowStep2 = '2. Open the installed adapter’s index or a common task below. Use draft task guides as supplementary guidance after checking their APIs against the release-matched adapter.'
  const lines = [
    '---',
    `name: ${spec.name}`,
    `description: ${JSON.stringify(`${spec.description} Use when a project uses ${spec.title} or when the task needs its setup, implementation, debugging, testing, migration, or integration guidance.`)}`,
    'license: MIT',
    'metadata:',
    '  tanstack-curation: "thematic-product"',
    `  tanstack-source-count: "${sourceCount}"`,
    '---',
    generatedComment,
    '',
    `# ${spec.title}`,
    '',
    spec.description,
    '',
  ]
  if (spec.maturity) lines.push('> ' + spec.maturity, '')
  lines.push(
    '## Workflow',
    '',
    '1. Inspect installed TanStack packages and exact versions.',
    workflowStep2,
    '3. Topic references are indexes. Choose one guide or section for the task; follow its prerequisite links only when needed.',
    '4. Prefer installed package types and version-matched source guidance over memory.',
    frameworkRoutes.length ? '5. Preserve headless/core behavior when translating examples to a framework adapter.' : '5. Validate the implementation with the project types and tests.',
    '',
    '## Task routing',
    '',
  )
  for (const entry of themes) {
    lines.push(`- [${entry.title}](references/${entry.key}.md) — ${entry.description}`)
  }
  if (spec.tasks?.length) {
    lines.push('', '## Common tasks', '')
    for (const [title, sourcePath] of spec.tasks) {
      const route = routes.find((entry) => entry.sourcePath === sourcePath)
      if (!route) throw new Error(`Missing task guide: ${spec.id}/${sourcePath}`)
      lines.push(`- [${title}](${route.file})`)
    }
  }
  if (frameworkRoutes.length) {
    lines.push('', '## Framework routing', '')
    for (const [framework, packageName, experimental] of frameworkRoutes) {
      const selectedTheme = frameworkReference(spec, themes, framework, foundationTheme)
      const link = selectedTheme ? ` Read [${selectedTheme.title}](references/${selectedTheme.key}.md).${selectedTheme.key === `framework-${framework}` ? '' : ' Shared guidance; check adapter-specific differences.'}` : ' No dedicated adapter guide is bundled; consult the installed package documentation.'
      lines.push(`- **${titleCase(framework)}** — detect \`${packageName}\`.${experimental ? ' Experimental adapter.' : ''}${link}`)
    }
    if (spec.frameworkNote) lines.push('', spec.frameworkNote)
  }
  if (spec.related?.length) {
    lines.push('', '## Product boundaries', '')
    lines.push(`Use these separate product skills when the task crosses their boundary: ${spec.related.map((name) => `\`${name}\``).join(', ')}.`)
  }
  if (docManifest) {
    const releases = docManifest.releasePackages.map((entry) => `${entry.name}@${entry.version}`).join(', ')
    lines.push('', '## Source status', '', `Official documentation from \`${docManifest.repository}\`, matched to these verified release inputs: ${releases}.`)
  }
  lines.push('', 'See [source provenance](references/SOURCES.md) for exact upstream inputs and deduplication records.', '')
  return lines.join('\n')
}

function buildOpenAiYaml(spec) {
  return [
    'interface:',
    `  display_name: ${JSON.stringify(spec.title)}`,
    `  short_description: ${JSON.stringify(`Task and framework guides for ${spec.title}`)}`,
    `  default_prompt: ${JSON.stringify(`Use $${spec.name} to implement this ${spec.title} task with the installed framework and package versions.`)}`,
    '',
  ].join('\n')
}

async function buildProduct(spec, primaryAtomic, atomicSkills, docSources, stageSkillsDir) {
  const ownAtomic = primaryAtomic.filter((source) => source.productId === spec.id)
  const supplemental = spec.supplementalAtomicMatch
    ? atomicSkills.filter((source) => spec.supplementalAtomicMatch(source.name)).map((source) => ({ ...source, supplemental: true }))
    : []
  const docs = docSources.byProduct.get(spec.id)
  const sources = [...ownAtomic, ...supplemental, ...(docs?.sources || [])]
    .sort((left, right) => sourcePriority(left) - sourcePriority(right) || ascii(left.id, right.id))
  if (!sources.length) throw new Error(`${spec.id} has no source material`)

  const themed = createThemeBuckets(spec)
  for (const source of sources) {
    const selected = selectTheme(spec, source, (fallback) => {
      process.stderr.write(
        `WARNING: ${source.id} has no curated theme in ${spec.id}; routing it to ${fallback.key}.\n`,
      )
    })
    themed.get(selected.key).sources.push(source)
  }
  const usedThemes = [...themed.values()].filter((entry) => entry.sources.length > 0)
  if (!usedThemes.length) throw new Error(`${spec.id} has no populated themes`)

  const productDir = join(stageSkillsDir, spec.name)
  await mkdir(join(productDir, 'references'), { recursive: true })
  const atomicAssetMap = await collectAtomicAssetMap(spec, sources, productDir)
  const docAssetMap = await collectDocAssetMap(docs, productDir)
  const atomicFileMap = new Map(atomicSkills.map((source) => [resolve(source.skillPath), source]))
  const atomicOriginById = new Map()
  const atomicOriginMap = new Map()
  const addAtomicOrigin = (origin, source) => {
    const normalized = posix.normalize(origin)
    const prior = atomicOriginMap.get(normalized)
    if (prior && prior.id !== source.id) throw new Error(`ambiguous atomic source path: ${normalized}`)
    atomicOriginMap.set(normalized, source)
  }
  for (const source of atomicSkills) {
    const packageDirectory = source.packageName.replace(/^@tanstack\//, '')
    const origin = posix.normalize(`packages/${packageDirectory}/skills/${source.sourcePath}/SKILL.md`)
    atomicOriginById.set(source.id, origin)
    addAtomicOrigin(origin, source)
    addAtomicOrigin(origin.replace(/^packages\//, ''), source)
    addAtomicOrigin(`packages/${packageDirectory}/skills/${packageDirectory}/${source.sourcePath}/SKILL.md`, source)
    addAtomicOrigin(`${packageDirectory}/skills/${packageDirectory}/${source.sourcePath}/SKILL.md`, source)
  }
  const atomicByPackage = Map.groupBy(atomicSkills, (source) => source.packageName)
  for (const [packageName, packageSources] of atomicByPackage) {
    const packageDirectory = packageName.replace(/^@tanstack\//, '')
    const roots = packageSources.filter((source) => source.metadata.get('tanstack-type') === 'core' && !source.sourcePath.includes('/'))
    for (const rootSource of roots) {
      for (const source of packageSources) {
        addAtomicOrigin(`packages/${packageDirectory}/skills/${rootSource.sourcePath}/${source.sourcePath}/SKILL.md`, source)
        addAtomicOrigin(`${packageDirectory}/skills/${rootSource.sourcePath}/${source.sourcePath}/SKILL.md`, source)
      }
    }
  }
  const atomicAliases = new Map([
    ['packages/react-router/skills/react-router/SKILL.md', 'tanstack-router-core'],
    ['packages/react-router/skills/compositions/router-query/SKILL.md', 'tanstack-query-intent-compositions-compose-query-with-t-d0bcdebe'],
    ['compositions/router-query/SKILL.md', 'tanstack-query-intent-compositions-compose-query-with-t-d0bcdebe'],
  ])
  const atomicByName = new Map(atomicSkills.map((source) => [source.name, source]))
  for (const [origin, name] of atomicAliases) {
    const source = atomicByName.get(name)
    if (!source) throw new Error(`missing atomic alias target: ${name}`)
    addAtomicOrigin(origin, source)
    addAtomicOrigin(origin.replace(/^packages\//, ''), source)
  }
  const docPathMap = new Map((docs?.sources || []).map((source) => [posix.normalize(source.sourcePath), source]))
  const sourceOutputMap = new Map()
  for (const entry of usedThemes) {
    for (const source of entry.sources) sourceOutputMap.set(source.id, { file: join(productDir, 'references', 'guides', `${guideId(source.id)}.md`), anchor: anchorFor(source), theme: entry.key })
  }

  const provenanceSources = []
  const duplicateDocuments = []
  const duplicateSections = []
  const routes = []
  await mkdir(join(productDir, 'references', 'guides'), { recursive: true })
  for (const entry of usedThemes) {
    const indexFile = join(productDir, 'references', `${entry.key}.md`)
    const indexLines = [`# ${entry.title}`, '', entry.description, '',
      'Choose the guide for the task. Each guide records its source and package version.', '',
      '| Guide | Source status | Package version |', '| --- | --- | --- |']
    const seenDocuments = new Map()
    const seenSections = new Map()
    for (const source of entry.sources) {
      const outputFile = sourceOutputMap.get(source.id).file
      const context = { source, outputFile, productDir, atomicAssetMap, docAssetMap,
        atomicFileMap, atomicOriginById, atomicOriginMap, docPathMap, sourceOutputMap }
      const sourceLink = relativeLink(indexFile, outputFile)
      indexLines.push(`| [${escapeTable(sourceLabel(source))}](${sourceLink}) | ${sourceStatus(source)} | \`${escapeTable(source.packageName)}@${escapeTable(source.packageVersion)}\` |`)
      const docHash = sha256(Buffer.from(normalizeText(source.body)))
      const priorDocument = seenDocuments.get(docHash)
      const kept = []
      if (priorDocument) {
        duplicateDocuments.push({ duplicate: source.id, canonical: priorDocument.id, theme: entry.key, sha256: docHash })
        kept.push({ heading: 'Canonical guidance', rewritten: true, content: `This source is an exact duplicate. Read [${sourceLabel(priorDocument)}](${relativeLink(outputFile, sourceOutputMap.get(priorDocument.id).file)}).\n` })
      } else {
        seenDocuments.set(docHash, source)
        for (const block of splitH2(source.body)) {
          const blockHash = sha256(Buffer.from(canonicalBlock(block)))
          const prior = seenSections.get(blockHash)
          if (prior) {
            duplicateSections.push({ duplicate: `${source.id}#${block.heading}`, canonical: `${prior.source.id}#${prior.block.heading}`, theme: entry.key, sha256: blockHash })
            const destination = relativeLink(outputFile, sourceOutputMap.get(prior.source.id).file)
            kept.push({ heading: block.heading, rewritten: true, content: `This section is an exact duplicate. Read [${prior.block.heading} in ${sourceLabel(prior.source)}](${destination}).\n` })
          } else {
            seenSections.set(blockHash, { source, block })
            kept.push(block)
          }
        }
      }
      const plan = planGuide(kept)
      const prerequisites = source.kind === 'atomic'
        ? parseJsonArray(source.metadata.get('tanstack-requires'), `prerequisites of ${source.id}`).map((id) => {
          const output = sourceOutputMap.get(id)
          return output ? { id, file: relative(productDir, output.file).split(sep).join('/') } : { id }
        }) : []
      const header = [
        `# ${sourceLabel(source)}`, '', `<a id="${anchorFor(source)}"></a>`, '',
        `${sourceStatus(source)} · \`${source.packageName}@${source.packageVersion}\`.`, '',
        ...(sourceStatus(source) === 'Draft guidance' ? ['This is unpublished draft guidance. Check APIs against the installed adapter and its release-matched documentation.', ''] : []),
        `[Topic index](${relativeLink(outputFile, indexFile)}) · [Source provenance](../SOURCES.md)`, '',
        ...prerequisites.filter((prerequisite) => prerequisite.file).map((prerequisite) => `Prerequisite: [${sourceLabel(sources.find((item) => item.id === prerequisite.id))}](${relativeLink(outputFile, join(productDir, prerequisite.file))}).`),
        ...(prerequisites.length ? [''] : []),
      ]
      const sourceExamples = []
      for (const example of examples.filter((item) => item.product === spec.id && item.sourcePath === source.sourcePath)) {
        const file = `references/examples/${example.file}`
        await mkdir(dirname(join(productDir, file)), { recursive: true })
        await copyFile(join(exampleDir, example.file), join(productDir, file))
        sourceExamples.push({ file, title: example.title, testedPackages: example.testedPackages })
        const tested = Object.entries(example.testedPackages).map(([name, version]) => `\`${name}@${version}\``).join(', ')
        header.push(`Runnable repository example: [${example.title}](${relativeLink(outputFile, join(productDir, file))}). Tested with ${tested}. This MIT-licensed example is maintained here; the official guidance follows.`, '')
      }
      const guideLines = [...header]
      const sectionRoutes = []
      if (plan.split) guideLines.push('## Choose a section', '', 'Read the overview or setup when it is a prerequisite, then the section needed for the task.', '')
      for (const page of plan.pages) {
        const pageFile = page.key ? outputFile.replace(/\.md$/, `--${page.key}.md`) : outputFile
        const pageLines = plan.split ? [`# ${sourceLabel(source)} — ${page.blocks[0].heading}`, '',
          `[Guide and prerequisites](${relativeLink(pageFile, outputFile)}) · ${sourceStatus(source)} · \`${source.packageName}@${source.packageVersion}\`.`, ''] : guideLines
        for (const block of page.blocks) {
          if (block.heading !== 'Overview') pageLines.push(`## ${block.heading}`, '')
          pageLines.push((block.rewritten ? block.content : rewriteLinks(block.content, { ...context, outputFile: pageFile })).trimEnd(), '')
        }
        const body = normalizeText(pageLines.join('\n'))
        if (plan.split) {
          await writeFile(pageFile, body)
          guideLines.push(`- [${page.blocks[0].heading}](${relativeLink(outputFile, pageFile)}) — ${Math.ceil(Buffer.byteLength(body) / 1024)} KiB`)
        }
        sectionRoutes.push({ title: page.blocks.map((block) => block.heading).join('; '), file: relative(productDir, pageFile).split(sep).join('/'), bytes: Buffer.byteLength(body) })
      }
      // Preserve original inbound fragments on split/duplicate guide entry points.
      if (plan.split || priorDocument) {
        guideLines.push('', '<!-- Original source anchors retained for inbound links. -->')
        for (const fragment of markdownHeadingFragments(source.body)) guideLines.push(`<a id="${fragment}"></a>`)
      }
      const guideBody = normalizeText(guideLines.join('\n'))
      await writeFile(outputFile, guideBody)
      routes.push({ id: source.id, title: sourceLabel(source), theme: entry.key, kind: source.kind,
        status: sourceStatus(source), frameworks: source.frameworks, package: source.packageName,
        version: source.packageVersion, file: relative(productDir, outputFile).split(sep).join('/'),
        sourcePath: source.sourcePath, bytes: Buffer.byteLength(guideBody), prerequisites, sections: sectionRoutes, examples: sourceExamples })
      provenanceSources.push(provenanceRecord(source, entry.key, priorDocument?.id || null))
    }
    await writeFile(indexFile, normalizeText(indexLines.join('\n')))
  }
  await writeFile(join(productDir, 'references', 'ROUTES.json'), json({ schemaVersion: 1, product: spec.id, guides: routes }))

  const licenseMap = new Map()
  const licenseInputs = []
  for (const source of sources.filter((entry) => entry.kind === 'atomic')) {
    const licenseFile = join(source.directory, 'LICENSE')
    if (await exists(licenseFile)) licenseInputs.push({ file: licenseFile, origin: source.id })
  }
  for (const license of docs?.manifest.licenses || []) {
    const licenseFile = join(docs.productRoot, ...license.outputPath.split('/'))
    licenseInputs.push({ file: licenseFile, origin: `${spec.id}:${license.sourcePath}`, expectedSha256: license.sha256 })
  }
  for (const input of licenseInputs) {
    const licenseFile = input.file
    const bytes = await readFile(licenseFile)
    const hash = sha256(bytes)
    if (input.expectedSha256 && input.expectedSha256 !== hash) throw new Error(`license hash mismatch: ${input.origin}`)
    if (!licenseMap.has(hash)) {
      const target = join(productDir, 'licenses', `${hash}.txt`)
      await mkdir(dirname(target), { recursive: true })
      await writeFile(target, bytes)
      licenseMap.set(hash, { path: relative(productDir, target).split(sep).join('/'), sources: [] })
    }
    licenseMap.get(hash).sources.push(input.origin)
  }
  await copyFile(join(root, 'LICENSE'), join(productDir, 'LICENSE'))

  const sourcesMarkdown = [
    '# Source provenance',
    '',
    '| Source | Kind | Theme | Package or repository | Version or commit | Deduplicated into |',
    '| --- | --- | --- | --- | --- | --- |',
    ...provenanceSources.map((source) =>
      `| \`${escapeTable(source.id)}\` | ${source.kind} | \`${source.theme}\` | \`${escapeTable(source.package || source.repository || '')}\` | \`${escapeTable(source.version || source.commit || '')}\` | ${source.duplicateOf ? `\`${escapeTable(source.duplicateOf)}\`` : ''} |`),
    '',
    `Exact duplicate documents replaced with canonical links: ${duplicateDocuments.length}. Exact duplicate H2 sections replaced with canonical links: ${duplicateSections.length}. No fuzzy deduplication is used.`,
    '',
  ]
  await writeFile(join(productDir, 'references', 'SOURCES.md'), sourcesMarkdown.join('\n'))

  const provenance = {
    schemaVersion: 1,
    generator,
    product: spec.id,
    sources: provenanceSources,
    duplicateDocuments,
    duplicateSections,
    licenses: [...licenseMap.entries()].sort(([left], [right]) => ascii(left, right)).map(([sha, value]) => ({ sha256: sha, path: value.path, sources: value.sources.sort(ascii) })),
    documentationVerification: docs ? {
      catalogSha256: docSources.manifest.catalog.sha256,
      verification: docSources.manifest.verification,
      repositoryArchives: docs.manifest.repositoryArchives,
      linkValidation: docs.manifest.linkValidation,
    } : undefined,
  }
  await writeFile(join(productDir, 'references', 'PROVENANCE.json'), json(provenance))
  await writeFile(join(productDir, 'SKILL.md'), buildRootSkill(spec, usedThemes, sources.length, docs?.manifest, routes))
  await mkdir(join(productDir, 'agents'), { recursive: true })
  await writeFile(join(productDir, 'agents', 'openai.yaml'), buildOpenAiYaml(spec))

  const marker = {
    generator,
    name: spec.name,
    product: spec.id,
    sourceCount: sources.length,
    themes: usedThemes.map((entry) => entry.key),
    guideCount: routes.length,
    largestGuideEntryBytes: Math.max(...routes.map((route) => route.bytes)),
    inputSha256: sha256(Buffer.from(json(provenance))),
  }
  await writeFile(join(productDir, productMarker), json(marker))
  await validateProduct(productDir, spec, usedThemes)
  return { spec, marker, themes: usedThemes }
}

function provenanceRecord(source, themeKey, duplicateOf) {
  return {
    id: source.id,
    kind: source.kind,
    theme: themeKey,
    package: source.packageName || undefined,
    version: source.packageVersion || undefined,
    repository: source.productManifest?.repository,
    commit: source.sourceCommit || source.productManifest?.commit,
    sourcePath: source.sourcePath,
    sha256: source.sha256,
    sourceKind: source.document?.sourceKind,
    verifiedCommits: source.document?.verifiedCommits,
    duplicateOf: duplicateOf || undefined,
  }
}

function escapeTable(value) {
  return String(value).replaceAll('|', '\\|').replaceAll('`', '\\`')
}

function markdownHeadingFragments(text) {
  const fragments = new Set()
  const counts = new Map()
  let fence = null
  for (const line of text.split('\n')) {
    const fenceMatch = line.match(/^\s*(```+|~~~+)/)
    if (fenceMatch) {
      const marker = fenceMatch[1]
      if (!fence) fence = { character: marker[0], length: marker.length }
      else if (fence.character === marker[0] && marker.length >= fence.length) fence = null
      continue
    }
    if (fence) continue
    const heading = line.match(/^\s{0,3}#{1,6}\s+(.+?)\s*#*\s*$/)
    if (!heading) continue
    const base = heading[1]
      .replace(/<[^>]*>/g, '')
      .normalize('NFKD')
      .replace(/\p{Diacritic}/gu, '')
      .toLowerCase()
      .replace(/[^\p{Letter}\p{Number}\s-]/gu, '')
      .trim()
      .replace(/\s+/gu, '-')
    if (!base) continue
    const occurrence = counts.get(base) || 0
    counts.set(base, occurrence + 1)
    fragments.add(occurrence ? `${base}-${occurrence}` : base)
  }
  return fragments
}

function hasMarkdownFragment(text, fragment) {
  const escaped = fragment.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  if (new RegExp(`<a\\s+id=["']${escaped}["']`, 'i').test(text)) return true
  return markdownHeadingFragments(text).has(fragment)
}

async function validateProduct(directory, spec, themes) {
  const rootSkill = join(directory, 'SKILL.md')
  const text = await readFile(rootSkill, 'utf8')
  const parsed = parseFrontmatter(text, rootSkill)
  if (parsed.name !== spec.name) throw new Error(`wrong product name in ${rootSkill}`)
  if (text.split('\n').length > 500) throw new Error(`product router exceeds 500 lines: ${rootSkill}`)
  for (const themeEntry of themes) {
    if (!(await exists(join(directory, 'references', `${themeEntry.key}.md`)))) {
      throw new Error(`missing theme reference: ${spec.id}/${themeEntry.key}`)
    }
  }
  const files = await walk(directory)
  const nestedSkills = files.filter((file) => file !== rootSkill && file.endsWith(`${sep}SKILL.md`))
  if (nestedSkills.length) throw new Error(`nested SKILL.md in ${spec.name}: ${nestedSkills[0]}`)
  for (const file of files.filter((entry) => dirname(entry) === join(directory, 'references') && /\.md$/i.test(entry))) {
    const bytes = (await stat(file)).size
    if (bytes > 100 * 1024) throw new Error(`reference exceeds 100 KiB: ${file} (${bytes} bytes)`)
    if (bytes > 90 * 1024) process.stderr.write(`WARNING: reference is above 90 KiB: ${file} (${bytes} bytes)\n`)
  }
  for (const file of files.filter((entry) => /\.(?:md|mdx)$/i.test(entry))) {
    const body = await readFile(file, 'utf8')
    let fence = null
    for (const line of body.split('\n')) {
      const fenceMatch = line.match(/^\s*(```+|~~~+)/)
      if (fenceMatch) {
        const marker = fenceMatch[1]
        if (!fence) fence = { character: marker[0], length: marker.length }
        else if (fence.character === marker[0] && marker.length >= fence.length) fence = null
        continue
      }
      if (fence) continue
      for (const match of line.matchAll(/https:\/\/[^\s<>"'`)]+/gi)) {
        if (isInsideInlineCode(line, match.index)) continue
        if (containsMutableRepositoryRef(match[0])) {
          throw new Error(`mutable repository reference in generated content: ${file} -> ${match[0]}`)
        }
      }
      for (const match of line.matchAll(/\]\(([^)]+)\)/g)) {
        if (isInsideInlineCode(line, match.index)) continue
        const raw = match[1].trim().replace(/^<|>$/g, '')
        const fragment = raw.includes('#') ? raw.slice(raw.indexOf('#') + 1).split('?')[0] : ''
        let target = raw.split(/[?#]/)[0]
        if (!target || target.startsWith('/') || /^(?:[a-z]+:|#)/i.test(target)) continue
        try {
          target = decodeURIComponent(target)
        } catch {
          throw new Error(`invalid encoded Markdown link: ${file} -> ${match[1]}`)
        }
        const resolved = resolve(dirname(file), target)
        if (!(await exists(resolved))) throw new Error(`broken generated link: ${file} -> ${match[1]}`)
        if (fragment && /\.(?:md|mdx)$/i.test(resolved)) {
          const decodedFragment = decodeURIComponent(fragment)
          const targetBody = await readFile(resolved, 'utf8')
          if (!hasMarkdownFragment(targetBody, decodedFragment)) {
            throw new Error(`broken generated fragment: ${file} -> ${match[1]}`)
          }
        }
      }
    }
  }
}

async function markAtomicsInternal(atomicSkills) {
  for (const source of atomicSkills) {
    let text = source.text
    if (/^  internal:\s*/m.test(text)) text = text.replace(/^  internal:\s*.*$/m, '  internal: true')
    else if (/^metadata:\s*$/m.test(text)) text = text.replace(/^metadata:\s*$/m, 'metadata:\n  internal: true')
    else {
      const end = text.indexOf('\n---', 4)
      if (end < 0) throw new Error(`missing frontmatter terminator: ${source.name}`)
      text = `${text.slice(0, end)}\nmetadata:\n  internal: true${text.slice(end)}`
    }
    await writeFile(source.skillPath, normalizeText(text))
  }
}

async function generatedDirectories() {
  const directories = []
  for (const entry of (await readdir(skillsDir, { withFileTypes: true })).sort((a, b) => ascii(a.name, b.name))) {
    if (!entry.isDirectory()) continue
    const directory = join(skillsDir, entry.name)
    for (const markerName of [productMarker, legacyMarker]) {
      const markerPath = join(directory, markerName)
      if (!(await exists(markerPath))) continue
      const marker = JSON.parse(await readFile(markerPath, 'utf8'))
      if (marker?.generator !== generator || marker?.name !== entry.name) {
        throw new Error(`refusing to replace invalid generated directory: ${directory}`)
      }
      directories.push(directory)
      break
    }
  }
  return directories
}

function buildCatalogFiles(results) {
  const byId = new Map(results.map((result) => [result.spec.id, result.spec]))
  const groupings = categoryGroups.map(([title, ids]) => ({
    title,
    description: `${title} product skills from the official TanStack public catalog.`,
    skills: ids.map((id) => byId.get(id)?.name || (() => { throw new Error(`missing catalog product ${id}`) })()),
  }))
  const skillsSh = {
    $schema: 'https://skills.sh/schemas/skills.sh.schema.json',
    notGrouped: 'bottom',
    groupings,
  }
  const marketplace = {
    name: 'tanstack-skills-extracted',
    description: 'Install one curated product skill for every public TanStack library.',
    owner: { name: 'lukasa1993' },
    plugins: groupings.map((group) => ({
      name: group.title.toLowerCase().replace(/[^a-z0-9]+/g, '-'),
      source: './',
      description: group.description,
      license: 'MIT',
      strict: false,
      skills: group.skills.map((name) => `./skills/${name}`),
    })),
  }
  return { skillsSh, marketplace }
}

async function installStage(stageRoot, results, atomicSkills) {
  const newSkillsDir = join(stageRoot, 'skills')
  const existingGenerated = await generatedDirectories()
  const existingSet = new Set(existingGenerated)
  for (const result of results) {
    const target = join(skillsDir, result.spec.name)
    if ((await exists(target)) && !existingSet.has(target)) {
      throw new Error(`refusing to replace non-generated skill directory: ${target}`)
    }
  }
  const backupRoot = join(root, `.tanstack-product-backup.tmp-${process.pid}`)
  if (await exists(backupRoot)) throw new Error(`refusing to overwrite stale backup: ${backupRoot}`)
  await mkdir(join(backupRoot, 'skills'), { recursive: true })
  await markAtomicsInternal(atomicSkills)
  const installedDirectories = []
  const catalogTargets = [
    [join(root, 'skills.sh.json'), join(backupRoot, 'skills.sh.json')],
    [join(root, '.claude-plugin', 'marketplace.json'), join(backupRoot, 'marketplace.json')],
  ]
  try {
    for (const directory of existingGenerated) {
      await rename(directory, join(backupRoot, 'skills', directory.split(sep).at(-1)))
    }
    for (const [target, backup] of catalogTargets) {
      if (await exists(target)) await rename(target, backup)
    }
    for (const result of results) {
      const target = join(skillsDir, result.spec.name)
      await rename(join(newSkillsDir, result.spec.name), target)
      installedDirectories.push(target)
    }
    await rename(join(stageRoot, 'skills.sh.json'), join(root, 'skills.sh.json'))
    await mkdir(join(root, '.claude-plugin'), { recursive: true })
    await rename(join(stageRoot, 'marketplace.json'), join(root, '.claude-plugin', 'marketplace.json'))
  } catch (error) {
    for (const directory of installedDirectories) {
      if (await exists(directory)) await rm(directory, { recursive: true, force: false })
    }
    for (const directory of existingGenerated) {
      const backup = join(backupRoot, 'skills', directory.split(sep).at(-1))
      if (await exists(backup)) await rename(backup, directory)
    }
    for (const [target, backup] of catalogTargets) {
      if (await exists(target)) await rm(target, { force: false })
      if (await exists(backup)) await rename(backup, target)
    }
    throw error
  } finally {
    if (await exists(backupRoot)) await rm(backupRoot, { recursive: true, force: true })
  }
}

async function main() {
  if (process.argv.length > 2) {
    if (process.argv.length === 3 && ['-h', '--help'].includes(process.argv[2])) {
      process.stdout.write('Usage: node scripts/build-groups.mjs\n')
      return
    }
    throw new Error('Usage: node scripts/build-groups.mjs')
  }
  if (JSON.stringify(productSpecs.map((spec) => spec.id)) !== JSON.stringify(expectedCatalogIds)) {
    throw new Error('product specification order does not match the public catalog')
  }
  const docSources = await readDocSources()
  const atomicSkills = await readAtomicSkills(docSources.docPackageOwners)
  const nonMitAtomics = atomicSkills.filter((source) => source.license.replace(/^['"]|['"]$/g, '') !== 'MIT')
  const nonMitDocuments = docSources.manifest.products.flatMap((entry) =>
    entry.releasePackages.filter((release) => release.license !== 'MIT').map((release) => `${release.name}@${release.version}:${release.license}`))
  if (nonMitAtomics.length || nonMitDocuments.length) {
    throw new Error(`mixed source licenses need an explicit policy: ${[
      ...nonMitAtomics.map((source) => `${source.id}:${source.license}`),
      ...nonMitDocuments,
    ].join(', ')}`)
  }
  const stageRoot = join(root, `.tanstack-product-build.tmp-${process.pid}`)
  if (await exists(stageRoot)) throw new Error(`refusing to overwrite stale stage: ${stageRoot}`)
  await mkdir(join(stageRoot, 'skills'), { recursive: true })
  let installed = false
  try {
    const results = []
    for (const spec of productSpecs) {
      results.push(await buildProduct(spec, atomicSkills, atomicSkills, docSources, join(stageRoot, 'skills')))
    }
    const { skillsSh, marketplace } = buildCatalogFiles(results)
    await writeFile(join(stageRoot, 'skills.sh.json'), json(skillsSh))
    await writeFile(join(stageRoot, 'marketplace.json'), json(marketplace))
    await installStage(stageRoot, results, atomicSkills)
    installed = true
    process.stdout.write(`Built ${results.length} product skills from ${atomicSkills.length} extracted skills and ${docSources.manifest.products.reduce((total, entry) => total + entry.documents.length, 0)} official documents.\n`)
  } finally {
    if (!installed && (await exists(stageRoot))) await rm(stageRoot, { recursive: true, force: true })
    if (installed && (await exists(stageRoot))) await rm(stageRoot, { recursive: true, force: true })
  }
}

main().catch((error) => {
  process.stderr.write(`ERROR: ${error?.stack || error}\n`)
  process.exitCode = 1
})
